--- 
title: "New York City Arrest Analysis"
author: "Ran Pan, Yi Yang"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
---

# Introduction

New York City's crime, its distribution as well as its trend is an interesting topic to be investigated. Usually, people analyze the topic from the number of crime counts' perspective. However, this time we will work from the number of arrest's perspective. From this different point of view, we can applied various techniques of exploratory analysis and visualizations to uncover the underlying insights and trends of New York City's crime environment. Specifically, we want to explore the characteristics of New York City’s crime among different boroughs, different age groups, different races. Additionally, we want to investigate how the crime characteristics change overtime. Lastly, we want to analyze whether Covid-19 pandemic has any impact on NYC's crime pattern. In the following sections, we will clean, preprocess, and analyze the data through visualizations as well as interactive graphs. The datasets are provided by NYPD and extracted from NYC Open Data. 
